window.activityData = [
  {
    id: "personal-ip",
    category: "IP成长",
    title: "打造你的个人IP",
    value: "从自身经历和优势出发，找到适合自己的个人IP方向。",
    highlights: ["定位梳理", "优势挖掘", "内容方向"],
    date: "待公布",
    time: "待公布",
    audience: "想做自媒体、打造个人品牌或探索知识变现的伙伴。",
    description: ["待公布"],
    gains: ["待公布"],
    schedule: [{ time: "待公布", item: "待公布" }],
    location: "待公布",
    format: "待公布",
    capacity: "待公布",
    price: "待公布",
    preparation: "待公布",
    status: "即将开始",
  },
  {
    id: "seedx-meetup",
    category: "伙伴链接",
    title: "SeedX群友见面交流会",
    value: "从群聊网友到真实伙伴，让想法找到可以一起行动的人。",
    highlights: ["自我介绍", "资源交换", "自由链接"],
    date: "待公布",
    time: "待公布",
    audience: "想认识群友、寻找资源、项目搭子和共创伙伴的人。",
    description: ["待公布"],
    gains: ["待公布"],
    schedule: [{ time: "待公布", item: "待公布" }],
    location: "待公布",
    format: "待公布",
    capacity: "待公布",
    price: "待公布",
    preparation: "待公布",
    status: "即将开始",
  },
  {
    id: "ai-obsidian-workshop",
    category: "AI实操",
    title: "AI + Obsidian个人知识库搭建专场",
    value: "让散落的收藏、灵感和经历，变成能持续产出的个人知识资产。",
    highlights: ["工具演示", "知识整理", "现场搭建"],
    date: "7月25日",
    time: "14:00–17:00",
    audience: "想建立个人知识系统，并用AI提升学习、输出和项目推进效率的人。",
    description: ["待公布"],
    gains: ["待公布"],
    schedule: [
      { time: "14:00", item: "为什么需要个人知识库" },
      { time: "14:15", item: "自我介绍" },
      { time: "14:45", item: "AI + Obsidian现场演示" },
      { time: "15:50", item: "从零搭建自己的知识库" },
      { time: "17:00", item: "合影收官" },
    ],
    location: "萧山区天人大厦",
    format: "线下实操工作坊",
    capacity: "限10人",
    price: "88元",
    preparation: "携带个人笔记本电脑",
    status: "已结束",
  },
  {
    id: "chat-monetization",
    category: "变现探索",
    title: "Chat｜打破内耗·靠近变现",
    value: "拆解内心卡点，找到更靠近收入的行动方向。",
    highlights: ["赚钱认知", "卡点拆解", "路径探索"],
    date: "7月26日",
    time: "14:00–17:30",
    audience: "处于Gap、转型或创业探索期，想突破心态卡点、寻找变现方向的人。",
    description: ["待公布"],
    gains: ["待公布"],
    schedule: [
      { time: "14:00", item: "自我介绍与卡点分享" },
      { time: "14:40", item: "重新理解赚钱" },
      { time: "15:00", item: "离钱最近的五件事" },
      { time: "15:15", item: "小组拆解与彼此赋能" },
      { time: "16:00", item: "普通人如何找到赚钱方向" },
      { time: "17:00", item: "赚钱高手和普通人的区别" },
      { time: "17:30", item: "合影收官" },
    ],
    location: "萧山区天人大厦",
    format: "小场深度线下交流",
    capacity: "限10人",
    price: "99元",
    preparation: "待公布",
    status: "已结束",
  },
];
