window.activityData = [
  {
    id: "seedx-meetup",
    category: "项目共创",
    title: "SeedX「下一步实验室」",
    value: "在真实交流中拆解卡点、对接资源，把“我想做”推进到“下一步做什么”。",
    highlights: ["破冰认脸", "Deep Talk", "资源连接"],
    date: "8月2日",
    time: "13:30签到｜14:00–17:00正式活动",
    audience: "有想法但还没开始、正在探索方向，或项目已启动但卡在需求、验证、伙伴或资源上的伙伴。",
    description: [
      "有想法但还没开始？正在探索方向？项目已经启动，但卡在需求、验证、伙伴或资源上？",
      "这周日，我们从不同视角共同聊同一个问题：如何让一个想法真正落地？",
      "不做泛泛而谈的分享会，在真实交流中发现不足，把“我想做”推进到“下一步做什么”。",
    ],
    gains: [
      "更清楚自己正在做或想做的事情，以及当前卡点",
      "围绕赚钱生意、AI杠杆、一人公司系统展开深度碰撞",
      "现场拆解项目卡点、对接资源、寻找共创伙伴",
    ],
    schedule: [
      { time: "13:30—14:00", item: "签到与自由认识" },
      { time: "14:00—14:10", item: "开场" },
      { time: "14:10—15:00", item: "自我介绍" },
      { time: "15:00—15:30", item: "话题碰撞" },
      { time: "15:30—16:00", item: "代表分享" },
      { time: "16:00—16:45", item: "自由交流" },
      { time: "16:45—17:00", item: "合影留念" },
    ],
    location: "芯模社区（报名后发送具体定位）",
    format: "线下小场深度交流",
    capacity: "限15人",
    price: "69元/人",
    preparation: "带着想法或项目来，想占位可私聊报名",
    status: "即将开始",
  },
  {
    id: "ai-obsidian-workshop",
    category: "AI实操",
    title: "AI + Obsidian个人知识库搭建专场",
    value: "让散落的收藏、灵感和经历，变成能持续产出的个人知识资产。",
    highlights: ["工具演示", "知识整理", "现场搭建"],
    date: "7月25日",
    time: "14:00–17:00",
    audience: "想建立个人知识系统，并用AI提升学习、输出和项目推进效率的人。",
    description: ["待公布"],
    gains: ["待公布"],
    schedule: [
      { time: "14:00", item: "为什么需要个人知识库" },
      { time: "14:15", item: "自我介绍" },
      { time: "14:45", item: "AI + Obsidian现场演示" },
      { time: "15:50", item: "从零搭建自己的知识库" },
      { time: "17:00", item: "合影收官" },
    ],
    location: "萧山区天人大厦",
    format: "线下实操工作坊",
    capacity: "限10人",
    price: "88元",
    preparation: "携带个人笔记本电脑",
    status: "已结束",
  },
  {
    id: "chat-monetization",
    category: "变现探索",
    title: "Chat｜打破内耗·靠近变现",
    value: "拆解内心卡点，找到更靠近收入的行动方向。",
    highlights: ["赚钱认知", "卡点拆解", "路径探索"],
    date: "7月26日",
    time: "14:00–17:30",
    audience: "处于Gap、转型或创业探索期，想突破心态卡点、寻找变现方向的人。",
    description: ["待公布"],
    gains: ["待公布"],
    schedule: [
      { time: "14:00", item: "自我介绍与卡点分享" },
      { time: "14:40", item: "重新理解赚钱" },
      { time: "15:00", item: "离钱最近的五件事" },
      { time: "15:15", item: "小组拆解与彼此赋能" },
      { time: "16:00", item: "普通人如何找到赚钱方向" },
      { time: "17:00", item: "赚钱高手和普通人的区别" },
      { time: "17:30", item: "合影收官" },
    ],
    location: "萧山区天人大厦",
    format: "小场深度线下交流",
    capacity: "限10人",
    price: "99元",
    preparation: "待公布",
    status: "已结束",
  },
];
